### PR TITLE
fix: type the event name to prevent unknown events

### PR DESCRIPTION
**Pull request by zzmp**
## Background

Events are defined in https://github.com/Uniswap/analytics-events, but typed as `string`, which leads to looser usage. For example, https://github.com/Uniswap/interface/pull/5748 introduces new events as strings, but defers their codified definition.

This change intends to add a speedbump, so that undefined events can still be used, but must be explicitly cast in order to get through the typechecker (eg `sendAnalyticsEvent('Undocumented Event Name' as EventName)`), which should encourage safer usage and - hopefully - faster definition of these events.

## Changes

- Types the eventName. This prevents unknown events from being added without first being vetted through analytics-events.

## Testing

- Typing-only change; no tests added or modified

### CODE REVIEW

**Comment by dannydaniil** [comment]
@zzmp the design decision to not make **analytics-events** a dependency to this repo was done on purpose to avoid tight coupling between the two packages and the dependency management thereof. 

Is there an important reason why you think we should make the change?

**Comment by zzmp** [comment]
> to avoid tight coupling between the two packages and the dependency management thereof

Including this as a peerDependency instead of a dependency decouples it enough such that the consumer will independently select their versions of each package.

> Is there an important reason why you think we should make the change?

I think it supports bad practices (eg https://github.com/Uniswap/interface/pull/5748), and risks events being created without being codified appropriately.

**Comment by adjkant** [comment]
With the upcoming reorg in https://github.com/Uniswap/analytics/pull/17, the `EventName` enum isn’t around anymore, If we want to add this typing, we could add a top-level `EventName` type that is a union of all the various `EventName` enums. It'd be good to wait for that to merge and ensure that's added, and make the dependency here the `2.0.0` version!

**Comment by dannydaniil** [comment]
@adjkant we can also make this a templated parameter and let the consuming client define the type. Otherwise, we need to keep expanding that top-level `EventName` each time we add client - not sure how many we will end up adding there.

@zzmp honestly, I don't like the coupling approach here, unless we somehow lock the dependency version. However, I do believe that its benefits are pretty big, so I'm actually for it too!

We should first figure out how this fits with @adjkant 's tho.

**Comment by zzmp** [comment]
I don't like using a templated parameter, because I think it is too easy to override (`sendAnalyticsEvent<string>('Event')` raises less flags than `sendAnalyticsEvent('Event' as EventName)`).

I think its worthwhile to couple and just expect analytics-events to always export an `EventName` union.

I'll move this to draft until https://github.com/Uniswap/analytics-events/pull/15 is out, and then refactor and we can resume discussion.

**Comment by dannydaniil** [comment]
@zzmp I was thinking of a templated parameter on the analytics client initialization by the consuming app. We could do that by refactoring the analytics client using a class. That would be more maintainable and easier to use

**Comment by adjkant** [comment]
@dannydaniil I think a parameter there ends up being more maintenance work and decentralizing from the `analytics-events` repo. I think the exported union type is easiest and that will be easily caught when testing added event enums + can be integrated into the repo process easily

**Comment by zzmp** [comment]
This would require all of the analytics-events extend a base event type.
I still think it's worth it - it's probably an hour of work to update analytics-events.
wdyt @dannydaniil @adjkant ?

**Comment by adjkant** [comment]
I'm up for it, though I think this maybe should be a major version update for both repos as a result to ensure that the typing for events is included.

All events would also not need to extend but it would need to be a union type of all event name enums. We will need to document that additional needed process in the analytics-events repo as well

**Pull request closed without merging**
